export enum NotificationsTypeEnum {
  COLLABORATION_ARTIST_DEACTIVATED = 'COLLABORATION_ARTIST_DEACTIVATED',
  COLLABORATION_AGENT_DEACTIVATED = 'COLLABORATION_AGENT_DEACTIVATED',
  COLLABORATION_FEEDBACK = 'COLLABORATION_FEEDBACK',

  VERIFICATION_ACCEPTED = 'VERIFICATION_ACCEPTED',
  VERIFICATION_DECLINED = 'VERIFICATION_DECLINED',

  EVENT_BOOKING_ACCEPTED = 'EVENT_BOOKING_ACCEPTED',

  EVENT_CANCELLED_AFTER_15_MIN = 'EVENT_CANCELLED_AFTER_15_MIN',
  EVENT_CANCELLED_BY_ARTIST = 'EVENT_CANCELLED_BY_ARTIST',
  EVENT_REMINDER_15_MINUTES = 'EVENT_REMINDER_15_MINUTES',
  EVENT_REMINDER_1_HOUR = 'EVENT_REMINDER_1_HOUR',
  EVENT_WAS_PROLONG = 'EVENT_WAS_PROLONG',
  EVENT_REMINDER = 'EVENT_REMINDER',
  EVENT_ENDED = 'EVENT_ENDED',

  PAYMENT_ARTIST_DEACTIVATED = 'PAYMENT_ARTIST_DEACTIVATED',
  PAYMENT_REFUND = 'PAYMENT_REFUND',

  PROMOTION_EXPIRE_1_HOUR = 'PROMOTION_EXPIRE_1_HOUR',
  PROMOTION_EXPIRE = 'PROMOTION_EXPIRE',
}
