name: CD

on:
  push:
    branches: [some-deploy-branch] # set branches (default `master`)

jobs:
  test:
    uses: broodd/nest-template/.github/workflows/ci.yaml@master

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          skip-on-empty: 'false'
          git-message: '{version}'
          github-token: ${{ secrets.github_token }}

      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      # - name: Deploy to GitHub Pages
      #   if: success()
      #   uses: crazy-max/ghaction-github-pages@v2
      #   with:
      #     target_branch: gh-pages
      #     build_dir: docs
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
