/**
 * [description]
 */
export enum ErrorTypeEnum {
  /*
   * GENERAL
   */
  ERROR_WITH_EMAIL_SENDING = 'ERROR_WITH_EMAIL_SENDING',
  INPUT_FILE_EMPTY_ERROR = 'INPUT_FILE_EMPTY_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  ALREADY_EXIST_ERROR = 'ALREADY_EXIST_ERROR',
  INPUT_DATA_ERROR = 'INPUT_DATA_ERROR',
  INPUT_FILE_ERROR = 'INPUT_FILE_ERROR',
  ROW_FORMAT_ERROR = 'ROW_FORMAT_ERROR',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',

  /**
   * FILES
   */
  FILE_UNSUPPORTED_TYPE = 'FILE_UNSUPPORTED_TYPE',
  FILE_ALREADY_EXIST = 'FILE_ALREADY_EXIST',
  FILES_NOT_FOUND = 'FILES_NOT_FOUND',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_TYPE_ERROR = 'FILE_TYPE_ERROR',

  /**
   * AUTH
   */
  AUTH_INCORRECT_CREDENTIALS = 'AUTH_INCORRECT_CREDENTIALS',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  NEW_PASSWORD_AND_OLD_PASSWORD_CANNOT_BE_SAME = 'NEW_PASSWORD_AND_OLD_PASSWORD_CANNOT_BE_SAME',
  AUTH_INCORRECT_CONFIRMATION_EMAIL_CODE = 'AUTH_INCORRECT_CONFIRMATION_EMAIL_CODE',
  AUTH_PASSWORDS_DO_NOT_MATCH = 'AUTH_PASSWORDS_DO_NOT_MATCH',

  /**
   * SOCKETS
   */
  SOCKET_ERROR = 'SOCKET_ERROR',

  /**
   * CHAT
   */
  CHAT_ALREADY_EXIST = 'CHAT_ALREADY_EXISTS',
  CHATS_NOT_FOUND = 'CHATS_NOT_FOUND',
  CHAT_NOT_FOUND = 'CHAT_NOT_FOUND',

  CHAT_MESSAGE_ALREADY_EXIST = 'CHAT_MESSAGE_ALREADY_EXIST',
  CHAT_MESSAGES_NOT_FOUND = 'CHAT_MESSAGES_NOT_FOUND',
  CHAT_MESSAGE_NOT_FOUND = 'CHAT_MESSAGE_NOT_FOUND',

  CHAT_PARTICIPANT_ALREADY_EXIST = 'CHAT_PARTICIPANT_ALREADY_EXIST',
  CHAT_PARTICIPANTS_NOT_FOUND = 'CHAT_PARTICIPANTS_NOT_FOUND',
  CHAT_PARTICIPANT_NOT_FOUND = 'CHAT_PARTICIPANT_NOT_FOUND',
}
