/**
 * [description]
 */
export enum ErrorTypeEnum {
  /*
   * GENERAL
   */
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  /**
   * FILES
   */
  FILE_UNSUPPORTED_TYPE = 'FILE_UNSUPPORTED_TYPE',
  FILE_ALREADY_EXIST = 'FILE_ALREADY_EXIST',
  FILES_NOT_FOUND = 'FILES_NOT_FOUND',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',

  /**
   * AUTH
   */
  AUTH_INCORRECT_CREDENTIALS = 'AUTH_INCORRECT_CREDENTIALS',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  NEW_PASSWORD_AND_OLD_PASSWORD_CANNOT_BE_SAME = 'NEW_PASSWORD_AND_OLD_PASSWORD_CANNOT_BE_SAME',
  AUTH_INCORRECT_CONFIRMATION_EMAIL_CODE = 'AUTH_INCORRECT_CONFIRMATION_EMAIL_CODE',
  AUTH_PASSWORDS_DO_NOT_MATCH = 'AUTH_PASSWORDS_DO_NOT_MATCH',

  /**
   * USER
   */
  USER_ALREADY_EXIST = 'USER_ALREADY_EXISTS',
  USERS_NOT_FOUND = 'USERS_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  /**
   * USER_REFRESH_TOKEN
   */
  USER_REFRESH_TOKEN_ALREADY_EXIST = 'USER_REFRESH_TOKEN_ALREADY_EXIST',
  USER_REFRESH_TOKENS_NOT_FOUND = 'USER_REFRESH_TOKENS_NOT_FOUND',
  USER_REFRESH_TOKEN_NOT_FOUND = 'USER_REFRESH_TOKEN_NOT_FOUND',

  /**
   * USER_NOTIFICATION_TOKEN
   */
  USER_NOTIFICATION_TOKEN_ALREADY_EXIST = 'USER_NOTIFICATION_TOKEN_ALREADY_EXIST',
  USER_NOTIFICATION_TOKENS_NOT_FOUND = 'USER_NOTIFICATION_TOKENS_NOT_FOUND',
  USER_NOTIFICATION_TOKEN_NOT_FOUND = 'USER_NOTIFICATION_TOKEN_NOT_FOUND',

  /**
   * NOTIFICATION
   */
  NOTIFICATIONS_ALREADY_EXIST = 'NOTIFICATIONS_ALREADY_EXIST',
  NOTIFICATION_ALREADY_EXIST = 'NOTIFICATION_ALREADY_EXIST',
  NOTIFICATIONS_NOT_FOUND = 'NOTIFICATIONS_NOT_FOUND',
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
}
